// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
	export interface GlobalComponents {
		BaseButton: typeof import('./../src/components/Common/BaseButton.vue')['default'];
		BaseSvg: typeof import('./../src/components/Common/BaseSvg.vue')['default'];
		HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default'];
		Scrollbar: typeof import('./../src/components/Base/Scrollbar/src/Scrollbar.vue')['default'];
		ScrollContainer: typeof import('./../src/components/Base/ScrollContainer/ScrollContainer.vue')['default'];
	}
}

export {};
